#include "header.h"

int i, k;
pthread_mutex_t msg_mutex = PTHREAD_MUTEX_INITIALIZER;

int log_count = 0;		//THIS WILL MAINTAIN THE COUNT OF ALL THEE FLIGHTS THAT LAND ON THE AIRPORT
void
send_response (pthread_t tid)
{
  unsigned int k = (int) tid;	//CHANGING THE FLIGHT NUMBER IN A UNIFORM FORMAT
  int j;
  unsigned int flight_number = k % 10000;	//THIS IS OUR FLIGHT NUMBER (which is randomly generated by the system in this case)
/* NOW WE VALIDATE THE FLIGHTS. 
   ACCORDING TO THE LOGIC FOLLOWED , IF A FLIGHT NUMBER IS A MULTIPLE OF 5, 
   IT IS SUPPOSED TO LAND AT THE AIRPORT .IF IT IS NOT A MULTIPLE OF 5, THEN IT 
   IS DIVERTED TO SOME ANOTHER CITY. 
*/

  if (k % 5 == 1)
    {
      printf
	("FLIGHT NO. %u \n\t PERMISSION DENIED... Please Go to MUMBAI ! \n\n\n",
	 flight_number);

    }

  else if (k % 5 == 2)
    {
      printf
	("FLIGHT NO. %u \n \t\t PERMISSION DENIED... Please Go to DELHI ! \n\n\n",
	 flight_number);

    }
  else if (k % 5 == 3)
    {
      printf
	("FLIGHT NO. %u \n \t PERMISSION DENIED... Please Go to HYDERABAD ! \n\n\n",
	 flight_number);

    }

  else if (k % 5 == 4)
    {
      printf
	("FLIGHT NO. %u \n \t\t PERMISSION DENIED... Please Go to KOLKATA !\n\n\n",
	 flight_number);

    }

  else
    {
    r:
      if (runway == 0 && count != 0)	//THE RUNWAY IS FREE BUT THE WAITING QUEUE IS NOT EMPTY.
	{

	  pthread_mutex_lock (&msg_mutex);	//LOCKING THE THREAD_MUTEX
	  runway = 1;
	  printf ("FLIGHT NO.%u \n PLEASE LAND !\n\n\n", pending[0]);
	  logg[log_count] = pending[0];
	  log_count++;
	  for (i = 0; i < (count - 1); i++)
	    pending[i] = pending[i + 1];
	  count--;
	  printf ("\n\ncount = %d\n", count);
	  if (count != 0)
	    {
	      for (i = 0; i < count; i++)
		printf ("\n\nFLIGHT NO. %u PLEASE WAIT !! \n\n", pending[i]);
	    }
	  sleep (2);
	  runway = 0;
	  pthread_mutex_unlock (&msg_mutex);	//UNLOCKING THE THREAD_MUTEX

	}

      else if (runway == 1)	//THE RUNWAY IS BUSY
	{

	  printf
	    ("FLIGHT NO. %u\nrunway is busy ... wait for a while..\n\n\n",
	     flight_number);
	  pending[count] = flight_number;
	  count++;
	  sleep (2);
	  runway = 0;
	  goto r;

	}

      else			//THE RUNWAY IS FREE AND THE QUEUE IS EMPTY
	{
	  pthread_mutex_lock (&msg_mutex);	//LOCKING THE THREAD_MUTEX
	  runway = 1;
	  printf ("FLIGHT NO. %u \tPLEASE LAND ....... \n", flight_number);
	  logg[log_count] = flight_number;
	  log_count++;
	  sleep (2);
	  runway = 0;
	  pthread_mutex_unlock (&msg_mutex);	//UNLOCKING THE THREAD_MUTEX
	}
    }
}
